.DEFAULT_GOAL: all
all: clean main
	./961.n-repeated-element-in-size-2n-array
clean:
	rm -fv 961.n-repeated-element-in-size-2n-array
main:
	gcc -o 961.n-repeated-element-in-size-2n-array 961.n-repeated-element-in-size-2n-array.c
